services:
  digitalhuman-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digitalhuman-server
    ports:
      - "18098:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - ./backend.env
    restart: unless-stopped
