services:
  digitalhuman-server:
    image: digitalhuman:latest
    container_name: digitalhuman-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18098:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - ./backend.env
    restart: unless-stopped

networks:
  default:
    name: digitalhuman-network
